#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if "RD_GLSL" in env["BUILDERS"]:
    gl_include_files = [str(f) for f in Glob("*_inc.glsl")]
    glsl_files = [str(f) for f in Glob("*.glsl") if str(f) not in gl_include_files]

    env.Depends([f + ".gen.h" for f in glsl_files], gl_include_files + ["#glsl_builders.py"])

    for glsl_file in glsl_files:
        env.RD_GLSL(glsl_file)
