#!/usr/bin/env python

Import("env")

if env["platform"] != "web":
    raise ValueError(
        'The WebGPU driver is only supported on platform "web" (via emdawnwebgpu).'
    )

driver_obj = []
env.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj
