#!/usr/bin/env python

Import("env")

thirdparty_dirs = []

backend = env["webgpu_backend"]
if backend == "auto":
    backend = "emdawnwebgpu" if env["platform"] == "web" else "dawn-desktop"

if backend == "dawn-desktop":
    env.Prepend(LIBS=["webgpu_dawn"])
    thirdparty_dirs += [
        "#thirdparty/dawn/include",
        "#thirdparty/dawn/include/webgpu",
    ]
elif backend == "emdawnwebgpu":
    pass
else:
    raise ValueError(
        'Unsupported "webgpu_backend=%s" for platform "%s".' % (backend, env["platform"])
    )

env.Prepend(CPPPATH=thirdparty_dirs)

driver_obj = []
env.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj
