#ifndef WEBGPU_CORRECTION_H
#define WEBGPU_CORRECTION_H

enum SpvTransformCorrectionType {
	SPIRV_WEBGPU_TRANSFORM_CORRECTION_TYPE_SPLIT_DREF_REGULAR = 0,
	SPIRV_WEBGPU_TRANSFORM_CORRECTION_TYPE_SPLIT_DREF_COMPARISON = 1,
	SPIRV_WEBGPU_TRANSFORM_CORRECTION_TYPE_SPLIT_COMBINED = 2,
	SPIRV_WEBGPU_TRANSFORM_CORRECTION_TYPE_SPLIT_BINDING_ARRAY = 3,
};

#endif // WEBGPU_CORRECTION_H
