#ifndef WEBGPU_BINDING_REMAP_H
#define WEBGPU_BINDING_REMAP_H

enum BindingRemapKind {
	WEBGPU_BINDING_REMAP_SPLIT_DREF_REGULAR = 0,
	WEBGPU_BINDING_REMAP_SPLIT_DREF_COMPARISON = 1,
	WEBGPU_BINDING_REMAP_SPLIT_COMBINED = 2,
	WEBGPU_BINDING_REMAP_SPLIT_BINDING_ARRAY = 3,
};

#endif // WEBGPU_BINDING_REMAP_H
